let conversation =[//-2
    ["narrator", "none"," You're a stray cat… "],
    ["narrator", "none","and one day, someone picked you up."],
    ["nemorin", "none","Poor little kitty… come with me."],
    ["narrator", "none","And just like that, you started living in his home"],
    ["nemorin", "happy","I'm hoooome~!"],
    ["nemorin", "happy","Did you miss me?"],
    ["the cat", "speechless","…meow"],
    ["nemorin", "normal","Hey hey hey—what's with that attitude?"],
    ["nemorin", "normal","You've been freeloading at my place for quite a while, "],
    ["nemorin", "normal"," I should really start charging you"],
    ["the cat", "speechless","What do you want?"],
    ["nemorin", "happy","Ta-daa! This!"],// show the progress
    ["nemorin", "normal","Find the Lost Souls."],
    ["nemorin", "normal"," You can see souls anyway,  it shouldn't be hard for you"],
    ["narrator", "none","Oh right, I forgot to mention—"],
    ["narrator", "none"," Nemorin is the big boss of the Soul-Reclaimers,"],
    ["narrator", "none"," responsible for collecting wandering spirits."],
    ["narrator", "none"," And you, a cat from the” NeitherWorld”,"],
    ["narrator", "none"," naturally have the ability to see souls."],
    ["the cat", "normal","So what exactly do you need me to do"],
    ["nemorin", "normal","Some souls are still lingering in the living world."],
    ["nemorin", "normal"," Find them and bring them back"],
    ["nemorin", "normal","Here's the first case file."],
    ["nemorin", "cry","Honestly… I don't want to be away from you…"],
    ["nemorin", "happy","But I've got no one else right now, so it's all on you."],
    ["nemorin", "happy","Don't miss me too much, okay?"],
    ["nemorin", "normal"," If you need anything, just call me."],
    ["nemorin", "normal"," I'm on standby 24h to… "],// move
    ["nemorin", "cry","Hey—I didn,t  finish my word!!"],
    ["the cat", "speechless","Ugh… humans are so noisy."],
    ["the cat", "speechless"," Whatever. Let's go"],
    // first part -------(-3) show the chapter transition
    ["the cat","normal","Should be around here…"],
    ["the cat","normal","Now… who is the lost soul?"],
    // ---- start part ----(-4) find people transition
    ["the cat","normal","Meow. Hello ,Can you see me?"],
    ["elderly woman","normal","......"],
    ["the cat","confuse","Can't you hear me ? I'm right here."],
    ["elderly woman","normal","......"],
    ["the cat","none","(pokes her)"],
    ["elderly woman","surprise","Oh! That scared me!"],
    ["elderly woman","surprise"," A… a little cat?"],
    ["the cat","normal","Hello."],
    ["elderly woman","confuse","…I must be exhausted…"],
    ["elderly woman","confuse"," Why am I hearing a cat… talk?"],
    ["the cat","normal","You didn't hear wrong actually."],
    ["elderly woman","normal","?! Then you must be some kind of… spirit-cat from “another world!"],
    ["narrator","none","Technically… She's not wrong."],
    ["the cat","confuse","Whatcha doing?"],
    ["elderly woman","normal","Me? I'm knitting a scarf."],
    ["elderly woman","normal","Winter is  coming. I want to knit one for my son, so he won't get cold."],
    ["the cat","confuse","And… where is your son?"],
    ["elderly woman","sad","......"],
    ["elderly woman","sad","… actually I haven't seen him in a long, long time…"],
    ["elderly woman","sad","I really want to see him again…"],
    ["elderly woman","sad"," I wonder what he looks like now."],
    ["narrator","none","already Found her 'lingering wish'"],
    ["narrator","none","Nemorin didn't find the wrong person — wait no, the wrong cat."],
    ["the cat ","normal","Do you want to see him right now?"],
    ["elderly woman","confuse","Oh? Why would you say that?And who even are you?"],
    ["the cat","normal","I'm a “Soul Guide."],
    ["the cat","normal"," You know what that means, don't you?"],
    ["elderly woman","surprise","It means… I'm already dead?"],
    ["elderly woman","sad","I see… that explains everything…"],
    ["elderly woman","surprise","But… Why are you taking me to see my son instead of leading me away?"],
    ["the cat","normal","Because I'm a kind cat."],
    ["the cat","normal","Now, can you tell me where he is?"],
    ["elderly woman","normal","Ah… OK."],
    ["narrator","none","Wow. Didn't hesitate at all."],
    ["narrator","none"," …Fine,  I'll shut up."],
    ["elderly woman","normal","To be honest… I don't know where he is ."],
    ["the cat","confuse","Huh?"],
    ["elderly woman","normal","I think I saw his workplace address somewhere… but I forgot where it is…"],
    ["elderly woman","confuse","It should be somewhere inside the house…"],
    ["narrator","none","Looks like you'll have to search the room."],//find 
    //-----------------------------------(-5)transition
    ["elderly woman","surprise","Ah—yes, yes! That's the place!"],
    ["the cat","normal","Great, then let's find him. It's close by."],
    ["elderly woman","confuse","But…How am I supposed to go anywhere?"],
    ["narrator","none"," “A cat only visible to the dead… and a wandering soul."],
    ["narrator","none","How are they supposed to travel?"],
    ["narrator","none","The easiest way would be to drive a car ."],
    ["narrator","none","But if a car starts moving on its own, someone might get scared "],
    ["narrator","none","Tomorrow's headlines would be something like—"],
    ["narrator","none","Car Moves on Its Own! Is This a New Supernatural Phenomenon?"],
    ["the cat","normal","You've got a car, right?"],
    ["the cat","normal"," I saw it —it should still work."],
    ["elderly woman","surprise","?! How did you just turn into a person?!"],
    ["narrator","none","Ah. Right. Forgot about that part."],
    ["the cat","normal","I'm a cat from the “NeitherWorld”, remember?"],
    ["the cat","normal"," Knowing a few tricks like this aren't hard."],
    ["the cat","normal"," So—where's the car key?"],
    ["elderly woman","normal","emm….. it's in my bedroom"],
    ["narrator","none","Of course to drive a car, grab the key little kitty—"],
    ["narrator","none"," Let's catch him before he gets off work."],
    //----------------------------------------------(-6)find get the key and out of the bed room
    ["the cat","normal","How should I address you?"],// in the car
    ["sereniel","normal","My name Serenie. And you?"],
    ["the cat","normal","Just call me the Cat."],
    ["the cat","normal"," So… could you tell me about you and your son?"],
    ["sereniel","sad","......"],
    ["sereniel","sad","We divorced a long time ago…"],
    ["sereniel","sad","When our son was about five or six years old."],
    ["sereniel","sad"," Before that, I was the one taking care of him."],
    ["sereniel","sad"," After the divorce… His father took him away."],
    ["sereniel","sad"," He wouldn't let me see him again."],
    ["sereniel","sad","I don't even know if Elio still remembers me…"],
    ["sereniel","sad"," Leo is my son's name."],
    ["the cat","confuse","(that's the Knight Commander's name…?)"],
    ["sereniel","normal","But seeing him on the news, living well…"],
    ["sereniel","normal"," That's enough for me."],
    ["sereniel","normal"," I don't really have to meet him."],
    ["sereniel","normal"," It'd be troublesome…"],
    ["sereniel","normal"," And what if I bother him?"],
    ["the cat","normal","We're already  here."],//comment
    //-------------------------------------------------(-7)
    ["sereniel","surprise","?! Already? That was so fast!"],
    ["narrator","none","Well, yeah. Teleportation devices are fast."],
    ["narrator","none","(Time to head inside and look for him.)"],// set the car
    //-----------------------------------------------(-8)// in comment
    ["receptionist","smile","Hello! How can I help you today?"],
    ["the cat","normal","Hi, I'm here to see Mr. Vallerin."],
    ["receptionist","smile","All right—do you have any appointment?"],
    ["the cat","sad","……"],
    ["the cat","sad","…No."],
    ["receptionist","normal","I'm sorry, but you'll need an appointment"],
    ["narrator","none","So what are you gonna do , little kitty?"],
    ["the cat","normal","Just call Mr.Vallerin and tell him Nemelin wants to see him."],
    ["receptionist","confuse","Eh? I'm sorry, but that's against company policy…"],
    ["the cat","normal","Call him. If anything happens, I'll take responsibility."],
    ["sereniel","normal","Maybe… let's not do that…"],
    ["vallerin","normal","What did you call me for ?"],
    ["vallerin","normal"," And please don't give my staff a hard time."],
    ["the cat","normal","Mr. Vallerin, your mother is dead."],
    ["the cat","normal","Come with me—we're handling her belongings."],
    ["vallerin","frown","…Sir, you must be mistaken."],
    ["vallerin","frown"," My mother is alive."],
    ["the cat","normal","I'm not talking about your stepmother."],
    ["the cat","normal","I mean your birth mother."],
    ["the cat","impatient","If your memory is that kind of  bad… how did you even get this job?"],
    ["vallerin","frown","What are you talking about?"],
    ["vallerin","frown"," I have only one mother—and she's perfectly fine."],
    ["the cat","confuse","?? What are you talking about?"],
    ["the cat","confuse","You seriously don't remember your own mother?"],
    ["vallerin","impatient","Sir, if you continue causing trouble, I'll have to call security."],
    ["the cat","surprise","Hey! Don't walk away!"],
    ["vallerin","impatient","Security. Please escort this gentleman out."],
    ["the cat","surprise","There's no way I've got the wrong person— at least let me finish before you leave!"],

];

// home npc --cople
let cople =[
    ["girl","That's weird… I feel like someone's staring at me."],
    ["boy","Honey, it's just your imagination. There's barely anyone on this street."],
    ["girl","…Wish so"],
];
// home npc 
let interaction =[
    ["young man","Changed to a child? Really?"],
    ["old man","It's definitely a woman you're looking for, not a man."],
    ["correct","…It's her."],
];
//  things in home map
let newspaper =[
    ["'A medium helping spirits solve cases for the police…'"],
    ["'A new Knight Commander sworn in'"],
    ["'A day in the life of the Knight Commander'"],
    ["'Shocking! The young Knight Commander turns out to be in his second marriage'"],
    ["'—and already has a son!'"],
];

let interactH =[
    ["TV", "Entertainment News: The Knight Commander is actually an illegitimate child!"],
    ["photo","You can't make out the face, but this must be her son."],
];